name: Build CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: pnpm/action-setup@latest
        with:
          version: 7
      - uses: actions/setup-node@latest
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint && pnpm run build